routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
Route::get('/', function() { return redirect()->route('login'); })->name('/');

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

Route::middleware('auth')->group(function () {
    // Profile
    Route::get('profile', 'ProfileController@index')->name('profile.index');
    Route::get('profile/edit', 'ProfileController@edit')->name('profile.edit');
    Route::patch('profile/update', 'ProfileController@update')->name('profile.update');
    // User
    Route::resource('user',   'UserController');
    // Room
    Route::resource('room', 'RoomController');
    // Member
    Route::resource('member', 'MemberController');
    // Repair
    Route::resource('repair', 'RepairController');
    Route::patch('/process/repair', 'RepairController@process')->name('process.repair');
    Route::patch('/success/repair', 'RepairController@success')->name('success.repair');
    // Change
    Route::resource('change', 'ChangeController');
    Route::post('approve/change/{change}', 'ChangeController@approve')->name('change.approve');
    Route::delete('cancel/change/{change}', 'ChangeController@cancel')->name('change.cancel');
    // Payment
    Route::resource('payment', 'PaymentController');
    Route::post('select/payment', 'PaymentController@select')->name('select.payment');
    Route::post('notification/payment', 'PaymentController@notification')->name('notification.payment');
    Route::post('notification/edit', 'PaymentController@notification_edit')->name('notification.edit');
    Route::post('approve/payment/{payment}', 'PaymentController@approve')->name('payment.approve');
    // History
    Route::get('history', 'HistoryController@index')->name('history.index');
    Route::get('history/{history}', 'HistoryController@show')->name('history.show');
    Route::get('history/print/{history}', 'HistoryController@print')->name('history.print');
});

app/Models/User.php
<?php

namespace App\Models;

use Illuminate\Notifications\Notifiable;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Spatie\Permission\Traits\HasRoles;

class User extends Authenticatable
{
    use Notifiable;
    use HasRoles;

    protected $fillable = [
        'first_name', 'last_name', 'email', 'phone', 'card_id', 'address','username', 'password',
    ];

    protected $hidden = [
        'password', 'remember_token',
    ];

    protected static function boot() {
        parent::boot();
        static::deleting(function($user) {
             $user->repair()->delete();
        });
    }

    public function getFullNameAttribute() {
        return $this->prefix. ' ' .$this->first_name. ' ' .$this->last_name;
    }

    public function room()
    {
        return $this->hasOne(Room::class);
    }

    public function repair()
    {
        return $this->hasMany(Repair::class);
    }
}

resources/views/layouts/template/footer.blade.php
<div class="clearfix"></div>
<footer>
    <div class="container-fluid">
        <p class="copyright">&copy; {{ Carbon::now()->year }} <a href="{{ route('home') }}"> All Rights Reserved </p>
     </div>
</footer>

resources/views/layouts/template/menu.blade.php
<!-- LEFT SIDEBAR -->
<div id="sidebar-nav" class="sidebar">
    <div class="sidebar-scroll">
        <nav>
            <ul class="nav">
                <li>
                    <a href="{{ route('home') }}" class="{{ starts_with(Request::route()->getName(), 'home') ? 'active' : '' }}">
                        <i class="lnr lnr-home"></i>
                        <span class="menu"> หน้าหลัก </span>
                    </a>
                </li>
                @foreach(menu() as $k => $v)
                @role($v['role'])
                <li>
                    <a href="{{ $v['route'] }}" class="{{ starts_with(Request::route()->getName(), $k) ? 'active' : '' }}" id="{{ $k }}">
                        <i class="lnr {{ $v['icon'] }}"></i>
                        <span class="menu"> {{ $v['name'] }} </span>
                    </a>
                </li>
                @endrole
                @endforeach
                @role('owner')
                <li>
                    <a href="#report" data-toggle="collapse" class="collapsed"><i class="lnr lnr-file-empty"></i> <span class="menu">รายงาน</span> <i class="icon-submenu lnr lnr-chevron-left"></i></a>
                    <div id="report" class="collapse">
                        <ul class="nav" >
                            <li><a href="{{ route('room.index')    }}" class="menu">ห้องพัก</a></li>
                            <li><a href="{{ route('member.index')  }}" class="menu">ผู้เช่าหอพัก</a></li>
                            <li><a href="{{ route('change.index')  }}" class="menu">แจ้งเปลี่ยนแปลงห้อง</a></li>
                            <li><a href="{{ route('payment.index') }}" class="menu">การชำระเงิน</a></li>
                            <li><a href="{{ route('history.index') }}" class="menu">ประวัติการชำระเงิน</a></li>
                        </ul>
                    </div>
                </li>
                @endrole
                <li>
                    <a href="{{ route('profile.index') }}" class="{{ starts_with(Request::route()->getName(), "profile") ? 'active' : '' }}">
                        <i class="lnr lnr-user"></i> <span class="menu"> โปรไฟล์ </span>
                    </a>
                </li>
                <li>
                    <a href="{{ route('logout') }}" onclick="event.preventDefault();document.getElementById('logout-form').submit();">
                        <i class="lnr lnr-exit"></i> <span class="menu"> ออกจากระบบ </span>
                    </a> {!! Form::open(['url' => 'logout', 'id'=>'logout-form']) !!} {!! Form::close() !!}
                </li>
            </ul>
        </nav>
    </div>
</div>
<!-- END LEFT SIDEBAR -->

resources/views/layouts/template/navbar.blade.php
<!-- NAVBAR -->
<nav class="navbar navbar-default navbar-fixed-top">
    <div class="brand">
        <a href="{{ route('home') }}">
            <span class="font"> หอพักบุญเต็มแมนชั่น </span>
        </a>
    </div>
    <div class="container-fluid">
        <div class="navbar-btn">
            <button type="button" class="btn-toggle-fullwidth"><i class="lnr lnr-arrow-left-circle"></i></button>
        </div>
        <div id="navbar-menu">
            <ul class="nav navbar-nav navbar-right">
                @role('admin')
                <li class="dropdown">
                    <a href="#" class="dropdown-toggle icon-menu" data-toggle="dropdown">
                            <span class="font"> แจ้งซ่อม </span><i class="lnr lnr-laptop-phone"></i>
                		<span class="badge bg-danger">{{ repair()['count'] != 0 ? repair()['count'] : NULL }}</span>
                	</a>
                    <ul class="dropdown-menu notifications">
                        @foreach(repair()['repair'] as $rs)
                        <li><a href="{{ route('repair.show', $rs->id) }}" class="notification-item"><span class="dot bg-primary"></span> {{ $rs->title }}</a></li>
                        @endforeach
                        <li><a href="{{ route('repair.index') }}" class="font text-center"> ดูทั้งหมด </a></li>
                    </ul>
                </li>
                <li class="dropdown">
                    <a href="#" class="dropdown-toggle icon-menu" data-toggle="dropdown">
                            <span class="font"> แจ้งเปลี่ยนแปลงห้อง </span><i class="lnr lnr-sync"></i>
                		<span class="badge bg-danger">{{ change()['count'] != 0 ? change()['count'] : NULL }}</span>
                	</a>
                    <ul class="dropdown-menu notifications">
                        @foreach(change()['change'] as $rs)
                        <li><a href="{{ route('change.show', $rs->id) }}" class="notification-item"><span class="dot bg-primary"></span> {{ $rs->from_number }} <span class="lnr lnr-arrow-right" style="font-size:16px"></span>  {{ $rs->to_number }} </a></li>
                        @endforeach
                        <li><a href="{{ route('change.index') }}" class="font text-center"> ดูทั้งหมด </a></li>
                    </ul>
                </li>
                <li class="dropdown">
                    <a href="#" class="dropdown-toggle icon-menu" data-toggle="dropdown">
                            <span class="font"> แจ้งชำระเงิน </span><i class="lnr lnr-alarm"></i>
                		<span class="badge bg-danger">{{ payment()['count'] != 0 ? payment()['count'] : NULL }}</span>
                	</a>
                    <ul class="dropdown-menu notifications">
                        @foreach(payment()['payment'] as $rs)
                        <li><a href="{{ route('payment.show', $rs->payment_id) }}" class="notification-item"><span class="dot bg-primary"></span> {{ "ห้อง ".$rs->payment->number }}</a></li>
                        @endforeach
                        <li><a href="{{ route('payment.index') }}" class="font text-center"> ดูทั้งหมด </a></li>
                    </ul>
                </li>
                @endrole

                @role('member')
                <li class="dropdown">
                    <a href="#" class="dropdown-toggle icon-menu" data-toggle="dropdown">
                            <span class="font"> แจ้งซ่อม </span><i class="lnr lnr-laptop-phone"></i>
                		<span class="badge bg-danger">{{ comfirm()['count'] != 0 ? comfirm()['count'] : NULL }}</span>
                	</a>
                    <ul class="dropdown-menu notifications">
                        @foreach(comfirm()['comfirm'] as $rs)
                        <li><a href="{{ route('repair.show', $rs->id) }}" class="notification-item"><span class="dot bg-primary"></span> {{ $rs->title }} </a></li>
                        @endforeach
                        <li><a href="{{ route('repair.index') }}" class="font text-center"> ดูทั้งหมด </a></li>
                    </ul>
                </li>
                <li class="dropdown">
                    <a href="#" class="dropdown-toggle icon-menu" data-toggle="dropdown">
                            <span class="font"> แจ้งชำระเงิน </span><i class="lnr lnr-alarm"></i>
                		<span class="badge bg-danger">{{ accept()['count'] ? accept()['count'] : NULL }}</span>
                	</a>
                    <ul class="dropdown-menu notifications">
                        @foreach(accept()['accept'] as $rs)
                        <li><a href="{{ route('payment.show', $rs->id) }}" class="notification-item"><span class="dot bg-primary"></span> {{ "ห้อง ".$rs->number }}</a></li>
                        @endforeach
                        <li><a href="{{ route('payment.index') }}" class="font text-center"> ดูทั้งหมด </a></li>
                    </ul>
                </li>
                @if(not()['count'])
                <li class="dropdown">
                    <a href="#" class="dropdown-toggle icon-menu" data-toggle="dropdown">
                            <span class="font"> ไม่อนุมัติชำระเงิน </span><i class="lnr lnr-cross"></i>
                		<span class="badge bg-danger">{{ not()['count'] }}</span>
                	</a>
                    <ul class="dropdown-menu notifications">
                        @foreach(not()['not'] as $rs)
                        <li><a href="{{ route('history.show', $rs->id) }}" class="notification-item"><span class="dot bg-primary"></span> {{ "ห้อง ".$rs->number }}</a></li>
                        @endforeach
                        <li><a href="{{ route('history.index') }}" class="font text-center"> ดูทั้งหมด </a></li>
                    </ul>
                </li>
                @endif
                @endrole

                <li class="dropdown">
                    <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                            {{ Html::image('image/user/user.png', NULL, ['class'=>'img-circle']) }}
                            <span> {{ Auth::user()->full_name }}  </span> <i class="icon-submenu lnr lnr-chevron-down"></i>
                        </a>
                    <ul class="dropdown-menu">
                        <li><a href="{{ route('profile.index') }}"><i class="lnr lnr-user"></i> <span class="menu"> โปรไฟล์ </span></a></li>
                        <li><a href="{{ route('logout') }}" onclick="event.preventDefault();document.getElementById('logout-form-menu').submit();">
                                <i class="lnr lnr-exit"></i> <span class="menu"> ออกจากระบบ </span>
                            </a>
                            {!! Form::open(['url' => 'logout', 'id'=>'logout-form-menu']) !!} {!! Form::close() !!}
                        </li>
                    </ul>
                </li>

            </ul>
        </div>
    </div>
</nav>
<!-- END NAVBAR -->