routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
Route::get('/', function() { return redirect()->route('login'); })->name('/');

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

Route::middleware('auth')->group(function () {
    // Profile
    Route::get('profile', 'ProfileController@index')->name('profile.index');
    Route::get('profile/edit', 'ProfileController@edit')->name('profile.edit');
    Route::patch('profile/update', 'ProfileController@update')->name('profile.update');
    // User
    Route::resource('user',   'UserController');
    // Room
    Route::resource('room', 'RoomController');
    // Member
    Route::resource('member', 'MemberController');
    // Repair
    Route::resource('repair', 'RepairController');
    Route::patch('/process/repair', 'RepairController@process')->name('process.repair');
    Route::patch('/success/repair', 'RepairController@success')->name('success.repair');
    // Change
    Route::resource('change', 'ChangeController');
    Route::post('approve/change/{change}', 'ChangeController@approve')->name('change.approve');
    Route::delete('cancel/change/{change}', 'ChangeController@cancel')->name('change.cancel');
    // Payment
    Route::resource('payment', 'PaymentController');
    Route::post('select/payment', 'PaymentController@select')->name('select.payment');
    Route::post('notification/payment', 'PaymentController@notification')->name('notification.payment');
    Route::post('notification/edit', 'PaymentController@notification_edit')->name('notification.edit');
    Route::post('approve/payment/{payment}', 'PaymentController@approve')->name('payment.approve');
    // History
    Route::get('history', 'HistoryController@index')->name('history.index');
    Route::get('history/{history}', 'HistoryController@show')->name('history.show');
    Route::get('history/print/{history}', 'HistoryController@print')->name('history.print');
});

app/Models/User.php
<?php

namespace App\Models;

use Illuminate\Notifications\Notifiable;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Spatie\Permission\Traits\HasRoles;

class User extends Authenticatable
{
    use Notifiable;
    use HasRoles;

    protected $fillable = [
        'first_name', 'last_name', 'email', 'phone', 'card_id', 'address','username', 'password',
    ];

    protected $hidden = [
        'password', 'remember_token',
    ];

    protected static function boot() {
        parent::boot();
        static::deleting(function($user) {
             $user->repair()->delete();
        });
    }

    public function getFullNameAttribute() {
        return $this->prefix. ' ' .$this->first_name. ' ' .$this->last_name;
    }

    public function room()
    {
        return $this->hasOne(Room::class);
    }

    public function repair()
    {
        return $this->hasMany(Repair::class);
    }
}

app/Http/Controllers/UserController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Models\User;

class UserController extends Controller
{
    function __construct()
    {
         $this->middleware('role:owner');
    }

    public function index()
    {
        return view('user.index')->withUsers(User::role('admin')->get());
    }

    public function create()
    {
        return view('user.create');
    }

    public function store(Request $request)
    {
        $message = [
            'username.unique' => 'มีผู้ใช้นี้แล้ว',
            'phone.unique'    => 'มีเบอร์โทรแล้ว',
        ];
        $request->validate([
            'username' => 'required|unique:users',
            'phone'    => 'required|unique:users',
            'password' => 'required',
            'email'    => 'required|email|unique:users',
        ]);
        $user = new User;
        $user->prefix     = $request->prefix;
        $user->first_name = $request->first_name;
        $user->last_name  = $request->last_name;
        $user->email      = $request->email;
        $user->phone      = $request->phone;
        $user->username   = $request->username;
        $user->password   = bcrypt('password');
        $user->save();
        $user->assignRole('admin');
        return redirect()->route('user.index')->with('success', "Success");
    }

    public function edit(User $user)
    {
        return view('user.edit')->withUser($user);
    }

    public function update(Request $request, User $user)
    {
        $message = [
            'username.unique' => 'มีผู้ใช้นี้แล้ว',
            'phone.unique'    => 'มีเบอร์โทรแล้ว',
        ];
        $request->validate([
            'username' => 'required|unique:users,username,'.$user->id,
            'phone'    => 'required|unique:users,phone,'.$user->id,
            'email'    => 'required|email|unique:users,email,'.$user->id
        ], $message);
        $user->prefix     = $request->prefix;
        $user->first_name = $request->first_name;
        $user->last_name  = $request->last_name;
        $user->email      = $request->email;
        $user->phone      = $request->phone;
        $user->username   = $request->username;
        $user->password   = isset($request->password) ? bcrypt($request->password) : $user->password;
        $user->save();
        return redirect()->route('user.index')->with('update', "Success");
    }

    public function destroy(User $user)
    {
        User::destroy($user->id);
        return redirect()->route('user.index')->with('delete', "Success");
    }
}

resources/views/user/create.blade.php
@extends('layouts.app')
@section('title', 'เพิ่มผู้ใช้งานระบบ')
@section('content')
<!-- MAIN -->
<div class="main">
    <!-- MAIN CONTENT -->
    <div class="main-content">
        <div class="container-fluid">
            <h3 class="page-title">
                {{ Breadcrumbs::render() }}
            </h3>
            <div class="row">
                <div class="col-md-12">
                    <!-- INPUTS -->
                    <div class="panel">
                        <div class="panel-heading">
                            <h3 class="panel-title"> เพิ่มผู้ใช้งานระบบ </h3>
                        </div>
                        @if ($errors->any())
                        <div class="alert alert-danger">
                            <ul>
                                @foreach ($errors->all() as $error)
                                <li>{{ $error }}</li>
                                @endforeach
                            </ul>
                        </div>
                        @endif
                        <div class="panel-body">
                            {!! Form::open(['route'=>'user.store']) !!}
                                {!! Form::label('prefix', 'คำนำหน้า', ['class'=>'font']) !!}
                                {!! Form::select('prefix', ['นาย'=> 'นาย', 'นาง'=>'นาง'], NULL,['class'=>'form-control', 'required']) !!}
                                <br>
                                {!! Form::label('First_name', 'ชื่อ', ['class'=>'font']) !!}
                                {!! Form::text('first_name', NULL, ['class'=>'form-control', 'placeholder'=>'First Name', 'required']) !!}
                                <br>
                                {!! Form::label('Last_name', 'นามสกุล', ['class'=>'font']) !!}
                                {!! Form::text('last_name', NULL, ['class'=>'form-control', 'placeholder'=>'Last Name', 'required']) !!}
                                <br>
                                {!! Form::label('Email', 'อีเมล์', ['class'=>'font']) !!}
                                {!! Form::email('email', NULL, ['class'=>'form-control', 'placeholder'=>'Email', 'required']) !!}
                                <br>
                                {!! Form::label('Phone', 'เบอร์โทร', ['class'=>'font']) !!}
                                {!! Form::tel('phone', NULL, ['class'=>'form-control phone', 'placeholder'=>'Tel.', 'required', 'maxlength'=> 10]) !!}
                                <br>
                                {!! Form::label('Username', 'ชื่อเข้าใช้ระบบ', ['class'=>'font']) !!}
                                {!! Form::text('username', NULL, ['class'=>'form-control', 'placeholder'=>'Username', 'required']) !!}
                                <br>
                                {!! Form::label('Password', 'รหัสผ่าน', ['class'=>'font']) !!}
                                {!! Form::password('password', ['class'=>'form-control', 'placeholder'=> 'Password']) !!}
                                <br>
                                <button class="btn btn-primary font" type="submit"> บันทึก </button>
                            {{ Form::close() }}
                        </div>
                    </div>
                    <!-- END INPUTS -->
                </div>
            </div>
        </div>
    </div>
    <!-- END MAIN CONTENT -->
</div>
<!-- END MAIN -->
@endsection
@push('scripts')
<script>
    $(".phone").keydown(function(e) {
        if ($.inArray(e.keyCode, [46, 8, 9, 27, 13, 110, 190]) !== -1 ||
        ((e.keyCode == 65 || e.keyCode == 86 || e.keyCode == 67) && (e.ctrlKey === true || e.metaKey === true)) ||(e.keyCode >= 35 && e.keyCode <= 40)) {
            return;
        }
        if ((e.shiftKey || (e.keyCode < 48 || e.keyCode > 57)) && (e.keyCode < 96 || e.keyCode > 105)) {
            e.preventDefault();
        }
    });
</script>
@endpush

resources/views/user/edit.blade.php
@extends('layouts.app')
@section('title', 'แก้ไขผู้ใช้งานระบบ')
@section('content')
<!-- MAIN -->
<div class="main">
    <!-- MAIN CONTENT -->
    <div class="main-content">
        <div class="container-fluid">
            <h3 class="page-title">
                {{ Breadcrumbs::render() }}
            </h3>
            <div class="row">
                <div class="col-md-12">
                    <!-- INPUTS -->
                    <div class="panel">
                        <div class="panel-heading">
                            <h3 class="panel-title"> แก้ไขผู้ใช้งานระบบ </h3>
                        </div>
                        @if ($errors->any())
                        <div class="alert alert-danger">
                            <ul>
                                @foreach ($errors->all() as $error)
                                <li>{{ $error }}</li>
                                @endforeach
                            </ul>
                        </div>
                        @endif
                        <div class="panel-body">
                            {!! Form::model($user, ['route'=> ['user.update', $user->id], 'method'=>'PATCH']) !!}
                                {!! Form::label('prefix', 'คำนำหน้า', ['class'=>'font']) !!}
                                {!! Form::select('prefix', ['นาย'=> 'นาย', 'นาง'=>'นาง'], NULL,['class'=>'form-control', 'required']) !!}
                                <br>
                                {!! Form::label('First_name', 'ชื่อ', ['class'=>'font']) !!}
                                {!! Form::text('first_name', NULL, ['class'=>'form-control', 'placeholder'=>'First Name', 'required']) !!}
                                <br>
                                {!! Form::label('Last_name', 'นามสกุล', ['class'=>'font']) !!}
                                {!! Form::text('last_name', NULL, ['class'=>'form-control', 'placeholder'=>'Last Name', 'required']) !!}
                                <br>
                                {!! Form::label('Email', 'อีเมล์', ['class'=>'font']) !!}
                                {!! Form::email('email', NULL, ['class'=>'form-control', 'placeholder'=>'Email', 'required']) !!}
                                <br>
                                {!! Form::label('Phone', 'เบอร์โทร', ['class'=>'font']) !!}
                                {!! Form::tel('phone', NULL, ['class'=>'form-control phone', 'placeholder'=>'Tel.', 'required' , 'maxlength'=> 10]) !!}
                                <br>
                                {!! Form::label('Username', 'ชื่อเข้าใช้ระบบ', ['class'=>'font']) !!}
                                {!! Form::text('username', NULL, ['class'=>'form-control', 'placeholder'=>'Username', 'required']) !!}
                                <br>
                                {!! Form::label('Password', 'รหัสผ่าน', ['class'=>'font']) !!}
                                {!! Form::password('password', ['class'=>'form-control', 'placeholder'=> 'Password']) !!}
                                <br>
                                <button class="btn btn-primary font" type="submit"> บันทึก </button>
                            {{ Form::close() }}
                        </div>
                    </div>
                    <!-- END INPUTS -->
                </div>
            </div>
        </div>
    </div>
    <!-- END MAIN CONTENT -->
</div>
<!-- END MAIN -->
@endsection
@push('scripts')
<script>
    $(".phone").keydown(function(e) {
        if ($.inArray(e.keyCode, [46, 8, 9, 27, 13, 110, 190]) !== -1 ||
        ((e.keyCode == 65 || e.keyCode == 86 || e.keyCode == 67) && (e.ctrlKey === true || e.metaKey === true)) ||(e.keyCode >= 35 && e.keyCode <= 40)) {
            return;
        }
        if ((e.shiftKey || (e.keyCode < 48 || e.keyCode > 57)) && (e.keyCode < 96 || e.keyCode > 105)) {
            e.preventDefault();
        }
    });
</script>
@endpush

resources/views/user/index.blade.php
@extends('layouts.app')
@section('title', 'User')
@section('content')
<!-- MAIN -->
<div class="main">
    <!-- MAIN CONTENT -->
    <div class="main-content">
        <div class="container-fluid">
            <h3 class="page-title">
                @role('owner')
                <a href="{{ route('user.create') }}" class="btn btn-primary btn-sm btn-create"> <i class="fa fa-plus" aria-hidden="true"></i> เพิ่มผู้ใช้งาน </a>
                @endrole
                {{ Breadcrumbs::render() }}
            </h3>
            <div class="row">
                <div class="col-md-12">
                    <!-- TABLE HOVER -->
                    <div class="panel">
                        <div class="panel-heading">
                            <h3 class="panel-title"> ข้อมูลผู้ใช้งาน </h3>
                        </div>
                        <div class="panel-body">
                            <div class="table-responsive">
                                <table class="table table-hover">
                                    <thead>
                                        <tr class="font">
                                            <th width="5%">#</th>
                                            <th width="20%">ชื่อ</th>
                                            <th width="20%">ชื่อเข้าใช้ระบบ</th>
                                            <th width="20%">อีเมล์</th>
                                            <th width="20%">เบอร์โทร</th>
                                            <th width="25%">ตัวเลือก</th>
                                        </tr>
                                    </thead>
                                    <tbody>
                                        @foreach($users as $k => $user)
                                        <tr class="text-center">
                                            <td class="text-center">{{ ++$k }}</td>
                                            <td>{{ $user->full_name }}</td>
                                            <td>{{ $user->username }}</td>
                                            <td>{{ $user->email }}</td>
                                            <td>{{ $user->phone }}</td>
                                            <td class="text-center">
                                                {{-- <a class="btn btn-success" href="{{ route('user.show', $user->id) }}"> <i class="fa fa-eye" aria-hidden="true"></i> </a> --}}
                                                <a class="btn btn-warning btn-edit" href="{{ route('user.edit', $user->id) }}"><i class="fa fa-pencil"></i></a>
                                                <button class="btn btn-danger btn-del"  data-id="{{ $user->id }}"><i class="fa fa-trash"></i></button>
                                                {{ Form::open(['method' => 'DELETE', 'route' => ['user.destroy', $user->id], 'id'=>'form-delete-'.$user->id]) }} {{ Form::close() }}
                                            </td>
                                        </tr>
                                        @endforeach
                                    </tbody>
                                </table>
                            </div>
                        </div>
                    </div>
                    <!-- END TABLE HOVER -->
                </div>
            </div>
        </div>
    </div>
    <!-- END MAIN CONTENT -->
</div>
<!-- END MAIN -->
@endsection
@push('scripts')
@if (session('success'))
<script>
    swal("Success!", "บันทึกข้อมูลเรียบร้อยแล้ว", "success");
</script>
@elseif (session('update'))
<script>
    swal("Updated!", "แก้ไขข้อมูลเรียบร้อยแล้ว", "success");
</script>
@elseif (session('delete'))
<script>
    swal("Deleted!", "ลบข้อมูลเรียบร้อยแล้ว", "success");
</script>
@endif
<script>
 $('.btn-del').on('click',function(){
    var id = $(this).data('id');
    swal({
        title: 'Are you sure?',
        text: "ต้องการที่จะลบ ผู้ใช้งาน นี้ใช่หรือไม่ !!",
        type: 'warning',
        showCancelButton: true,
        confirmButtonColor: '#3085d6',
        cancelButtonColor: '#d33',
        confirmButtonText: 'ตกลง',
        cancelButtonText: 'ยกเลิก'
    }).then((result) => {
    if (result.value) {
        $( "#form-delete-"+id ).submit();
    }
    });
 });
</script>
@endpush